// <auto-generated />
using System;
using LevelUpGym.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LevelUpGym.Api.Migrations
{
    [DbContext(typeof(LevelUpDbContext))]
    [Migration("20260513224356_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LevelUpGym.Api.Models.Auth", b =>
                {
                    b.Property<int>("IdAuth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdAuth"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdProfile")
                        .HasColumnType("int");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdAuth");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdProfile")
                        .IsUnique();

                    b.ToTable("auth", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.CashMovement", b =>
                {
                    b.Property<int>("IdMovimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMovimiento"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdMovimiento");

                    b.ToTable("CashMovements");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Category", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Client", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("IdProfile")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCliente");

                    b.HasIndex("IdProfile")
                        .IsUnique();

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Employee", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEmpleado"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("FechaContratacion")
                        .HasColumnType("date");

                    b.Property<int?>("IdEps")
                        .HasColumnType("int");

                    b.Property<int>("IdProfile")
                        .HasColumnType("int");

                    b.Property<decimal?>("SalarioBase")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("IdEps");

                    b.HasIndex("IdProfile")
                        .IsUnique();

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.EmployeePayment", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("EmployeeIdEmpleado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("date");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPago");

                    b.HasIndex("EmployeeIdEmpleado");

                    b.ToTable("EmployeePayments");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Eps", b =>
                {
                    b.Property<int>("IdEps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEps"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEps");

                    b.ToTable("EpsList");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Tipo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdItem");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Membership", b =>
                {
                    b.Property<int>("IdMembresia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdMembresia"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdItem")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdMembresia");

                    b.HasIndex("IdItem")
                        .IsUnique()
                        .HasFilter("[IdItem] IS NOT NULL");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasFilter("[Nombre] IS NOT NULL");

                    b.ToTable("membresias", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.PaymentMethod", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPago");

                    b.ToTable("PaymentMethods");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Permission", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPermiso"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Product", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int?>("IdItem")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal?>("PrecioVenta")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdProducto");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdItem")
                        .IsUnique()
                        .HasFilter("[IdItem] IS NOT NULL");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasFilter("[Nombre] IS NOT NULL");

                    b.ToTable("productos", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Profile", b =>
                {
                    b.Property<int>("IdProfile")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProfile"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumDocumento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdProfile");

                    b.HasIndex("NumDocumento")
                        .IsUnique();

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Progress", b =>
                {
                    b.Property<int>("IdProgreso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProgreso"));

                    b.Property<string>("Altura")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("ClientIdCliente")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaMedicion")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Imc")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdProgreso");

                    b.HasIndex("ClientIdCliente");

                    b.ToTable("ProgressReports");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Provider", b =>
                {
                    b.Property<int>("IdProveedor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProveedor"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdProveedor");

                    b.ToTable("Providers");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Purchase", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCompra"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdProveedor")
                        .HasColumnType("int");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdProveedor");

                    b.HasIndex("MetodoPago");

                    b.ToTable("compras", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.PurchaseDetail", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int?>("IdProducto")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ProductIdProducto")
                        .HasColumnType("int");

                    b.Property<int?>("PurchaseIdCompra")
                        .HasColumnType("int");

                    b.Property<decimal?>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDetalle");

                    b.HasIndex("ProductIdProducto");

                    b.HasIndex("PurchaseIdCompra");

                    b.ToTable("PurchaseDetails");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Role", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdPermiso")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("PermissionIdPermiso")
                        .HasColumnType("int");

                    b.Property<int?>("RoleIdRol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PermissionIdPermiso");

                    b.HasIndex("RoleIdRol");

                    b.HasIndex("IdRol", "IdPermiso")
                        .IsUnique()
                        .HasFilter("[IdRol] IS NOT NULL AND [IdPermiso] IS NOT NULL");

                    b.ToTable("roles_permisos", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Sale", b =>
                {
                    b.Property<int>("IdVenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdVenta"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("int");

                    b.Property<decimal?>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdVenta");

                    b.HasIndex("IdCliente");

                    b.HasIndex("MetodoPago");

                    b.ToTable("ventas", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.SaleDetail", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDetalle"));

                    b.Property<int?>("Cantidad")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdItem")
                        .HasColumnType("int");

                    b.Property<int?>("IdVenta")
                        .HasColumnType("int");

                    b.Property<int?>("ItemIdItem")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecioUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SaleIdVenta")
                        .HasColumnType("int");

                    b.Property<decimal?>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdDetalle");

                    b.HasIndex("ItemIdItem");

                    b.HasIndex("SaleIdVenta");

                    b.ToTable("SaleDetails");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Subscription", b =>
                {
                    b.Property<int>("IdSuscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdSuscripcion"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEstado")
                        .HasColumnType("int");

                    b.Property<int>("IdMembresia")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdSuscripcion");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEstado");

                    b.HasIndex("IdMembresia");

                    b.ToTable("suscripciones", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.SubscriptionStatus", b =>
                {
                    b.Property<int>("IdEstado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdEstado"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("IdEstado");

                    b.ToTable("SubscriptionStatuses");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AuthIdAuth")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IdAuth")
                        .HasColumnType("int");

                    b.Property<int?>("IdRol")
                        .HasColumnType("int");

                    b.Property<int?>("RoleIdRol")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthIdAuth");

                    b.HasIndex("RoleIdRol");

                    b.HasIndex("IdAuth", "IdRol")
                        .IsUnique()
                        .HasFilter("[IdAuth] IS NOT NULL AND [IdRol] IS NOT NULL");

                    b.ToTable("usuarios_roles", (string)null);
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Auth", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Profile", "Profile")
                        .WithOne("Auth")
                        .HasForeignKey("LevelUpGym.Api.Models.Auth", "IdProfile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Client", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Profile", "Profile")
                        .WithOne("Client")
                        .HasForeignKey("LevelUpGym.Api.Models.Client", "IdProfile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Employee", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Eps", "Eps")
                        .WithMany("Employees")
                        .HasForeignKey("IdEps");

                    b.HasOne("LevelUpGym.Api.Models.Profile", "Profile")
                        .WithOne("Employee")
                        .HasForeignKey("LevelUpGym.Api.Models.Employee", "IdProfile")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Eps");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.EmployeePayment", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Employee", "Employee")
                        .WithMany("Payments")
                        .HasForeignKey("EmployeeIdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Membership", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Item", "Item")
                        .WithOne("Membership")
                        .HasForeignKey("LevelUpGym.Api.Models.Membership", "IdItem");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Product", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("IdCategoria");

                    b.HasOne("LevelUpGym.Api.Models.Item", "Item")
                        .WithOne("Product")
                        .HasForeignKey("LevelUpGym.Api.Models.Product", "IdItem");

                    b.Navigation("Category");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Progress", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Client", "Client")
                        .WithMany("ProgressReports")
                        .HasForeignKey("ClientIdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Purchase", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Provider", "Provider")
                        .WithMany("Purchases")
                        .HasForeignKey("IdProveedor");

                    b.HasOne("LevelUpGym.Api.Models.PaymentMethod", "PaymentMethodNavigation")
                        .WithMany("Purchases")
                        .HasForeignKey("MetodoPago");

                    b.Navigation("PaymentMethodNavigation");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.PurchaseDetail", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Product", "Product")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("ProductIdProducto");

                    b.HasOne("LevelUpGym.Api.Models.Purchase", "Purchase")
                        .WithMany("Details")
                        .HasForeignKey("PurchaseIdCompra");

                    b.Navigation("Product");

                    b.Navigation("Purchase");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.RolePermission", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionIdPermiso");

                    b.HasOne("LevelUpGym.Api.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleIdRol");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Sale", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Client", "Client")
                        .WithMany("Sales")
                        .HasForeignKey("IdCliente");

                    b.HasOne("LevelUpGym.Api.Models.PaymentMethod", "PaymentMethodNavigation")
                        .WithMany("Sales")
                        .HasForeignKey("MetodoPago");

                    b.Navigation("Client");

                    b.Navigation("PaymentMethodNavigation");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.SaleDetail", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Item", "Item")
                        .WithMany("SaleDetails")
                        .HasForeignKey("ItemIdItem");

                    b.HasOne("LevelUpGym.Api.Models.Sale", "Sale")
                        .WithMany("Details")
                        .HasForeignKey("SaleIdVenta");

                    b.Navigation("Item");

                    b.Navigation("Sale");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Subscription", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Client", "Client")
                        .WithMany("Subscriptions")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelUpGym.Api.Models.SubscriptionStatus", "Status")
                        .WithMany("Subscriptions")
                        .HasForeignKey("IdEstado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LevelUpGym.Api.Models.Membership", "Membership")
                        .WithMany("Subscriptions")
                        .HasForeignKey("IdMembresia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Membership");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.UserRole", b =>
                {
                    b.HasOne("LevelUpGym.Api.Models.Auth", "Auth")
                        .WithMany("UserRoles")
                        .HasForeignKey("AuthIdAuth");

                    b.HasOne("LevelUpGym.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleIdRol");

                    b.Navigation("Auth");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Auth", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Client", b =>
                {
                    b.Navigation("ProgressReports");

                    b.Navigation("Sales");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Employee", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Eps", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Item", b =>
                {
                    b.Navigation("Membership");

                    b.Navigation("Product");

                    b.Navigation("SaleDetails");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Membership", b =>
                {
                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.PaymentMethod", b =>
                {
                    b.Navigation("Purchases");

                    b.Navigation("Sales");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Product", b =>
                {
                    b.Navigation("PurchaseDetails");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Profile", b =>
                {
                    b.Navigation("Auth");

                    b.Navigation("Client");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Provider", b =>
                {
                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Purchase", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.Sale", b =>
                {
                    b.Navigation("Details");
                });

            modelBuilder.Entity("LevelUpGym.Api.Models.SubscriptionStatus", b =>
                {
                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
